<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "report".
 *
 * @property int $id
 * @property int $document_type
 * @property int $year
 * @property int $month
 * @property int $user_id
 * @property int $status
 * @property string $created_date
 * @property string $closed_date
 */
class Report extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'report';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes'=>[
                    ActiveRecord::EVENT_BEFORE_INSERT =>['created_date']
                ],
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['document_type', 'year', 'month', 'user_id', 'status'], 'required'],
            [['document_type', 'year', 'month', 'status'], 'integer'],
            [['created_date', 'closed_date','user_id'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'document_type' => 'Hisobot kategoriyasi',
            'year' => 'Yil',
            'month' => 'Oy',
            'user_id' => "Ma'sul shaxs",
            'status' => 'Holat',
            'created_date' => 'Yaratilgan vaqti',
            'closed_date' => 'Qabul qilingan vaqti',
        ];
    }

    public function beforeDelete()
    {
        switch ($this->document_type){
            case 1:

                $ids = ArrayHelper::map(ReportOffense::find()->where(['report_id'=>$this->id])->all(),'id','id');
                ReportOffense::deleteAll($ids);

                break;
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
